"                                                     \n\
                       Help                           \n\
                                                      \n\
      Move cursor up ...................... k         \n\
      Move cursor down .................... j         \n\
      Edit task ........................... e         \n\
      View this help screen ............... h         \n\
      Quit ................................ q         \n\
      Save changes ........................ s         \n\
                                                      \n\
";
